name: Echo Ishay and Actor

on:
  push:

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say the truth
        run: echo "Ishay is the king"

      - name: Who pushed?
        run: echo "Pushed by: ${{ github.actor }}"

